### ISSUE TITLE
Avoid fetching all entries in peopleRelay

### ISSUE THREAD

**Issue by KATT** [leebenson/graphql-with-sequelize#2]
Hey!

I've just started playing around with this. It's a great introduction!

[Here](https://github.com/leebenson/graphql-with-sequelize/blob/b10351e7bfce1076d9539139f35f0e63daf93154/schema-relay.js#L115) we're fetching all `person` entries and let the graphql-relay lib do the pagination. How would you go about this if you want to make sure you could do pagination without fetching all the entries?

**Comment by KATT** [comment]
Yay, I managed to do a very simple version that does it. :tada: 

<img width="901" alt="screen shot 2016-02-03 at 18 25 41" src="https://cloud.githubusercontent.com/assets/459267/12795933/a05a6270-caa3-11e5-996d-da6580ed18b2.png">

<img width="903" alt="screen shot 2016-02-03 at 18 25 58" src="https://cloud.githubusercontent.com/assets/459267/12795938/a67c5596-caa3-11e5-9421-5dcd7f642e56.png">

here's my code:

``` js
peopleRelay: {
      type: PersonConnection,
      description: 'Person connection test',
      args: connectionArgs,
      async resolve (root, args) {
        const {first, after} = args;

        const query = {
          offset: 0
        };
        if (first) {
          query.limit = first;
        }

        if (after) {
          const decoded = new Buffer(after, 'base64').toString();
          const [arrayconnection, offset] = decoded.split(':');
          query.offset = parseInt(offset, 10) + 1;
        }


        const {count, rows} = await Db.models.person.findAndCountAll(query);
        const meta = {
          sliceStart: query.offset,
          arrayLength: count
        };

        return connectionFromArraySlice(rows, args, meta);
      }
    },
```

Could (should) be externalised and made generic, but that's a simple version of making it.

Have you had another approach in mind?

**Comment by KATT** [comment]
Going on hols tomorrow, but I'll be working on it on this branch when I'm back https://github.com/KATT/graphql-with-sequelize/tree/feature/relay

**Comment by leebenson** [comment]
Sorry for the silence in this thread, I'm only just seeing it. TBH, Relay is outside the scope of this tutorial. I had originally intended to explore it further, but with Relay 2 around the corner and other libs like Apollo available now, decided to leave that as an exercise for the user.

Feel free to develop on it further, though - I'd certainly accept any PRs that demonstrate the concepts in action.
