### ISSUE TITLE
Split into folders

### ISSUE THREAD

**Issue by julianmnst** [leebenson/graphql-with-sequelize#6]
Hi there @leebenson ! I have a simple question. How would one split the schema into maybe separate folders or at least files to make it easier to mantain? Thanks in advance!

**Comment by leebenson** [comment]
@julianmnst - check out https://github.com/reactql/examples/tree/master/auth, which is a project I created based on my https://reactql.org starter kit (which I'd highly recommend using!)

You can see in the [src folder](https://github.com/reactql/examples/tree/master/auth/src) how source is split into:

- Separate `.gql` queries and mutations (`src/gql`)
- GraphQL schema (`src/graphql`)

This layout goes way further that what I demonstrate in the simple graphql-with-sequelize project, and the starter kit comes with a ton of functionality beyond - see https://github.com/reactql/kit for features.
